apiVersion: v1
kind: Service
metadata:
  name: cadence-matching
spec:
  selector:
    app.kubernetes.io/component: matching
  ports:
    - name: grpc
      port: 7835
      targetPort: 7835
    - name: rpc
      port: 7935
      targetPort: 7935
