apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cadence-kind-lab
resources:
  - ../../base
patches:
  - path: matching-a-resources.yaml
  - path: matching-b-resources.yaml
  - path: matching-c-resources.yaml
